version: '3.9'

services:
    python:
        container_name: python
        build: 
            context: ./python
            dockerfile: Dockerfile
        volumes:
            - ./python/app:/app
        ports:
            - "8000:8000"  # 必要に応じて
        tty: true
